version: "2.1"
services:
  app:
    build:
      context: ./
    depends_on:
      - datadog
    command: ["./wait-for-datadog.sh", "localhost", "5555", "python app.py"]
    privileged: true
    tty: true
    restart: always
    network_mode: host
  # Based on https://github.com/balena-io-examples/balena-datadog/issues/5#issuecomment-770284780
  # and https://docs.datadoghq.com/agent/docker/log/?tab=containerinstallation
  datadog:
    image: datadog/agent-arm64:7.25.0
    environment:
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE=name:datadog name:balena_supervisor
      - DD_HEALTH_PORT=5555
      - DD_TAGS=custom_tag:foo
      # Required for "Log Collection Only."
      - DD_ENABLE_PAYLOADS_EVENTS=false
      - DD_ENABLE_PAYLOADS_SERIES=false
      - DD_ENABLE_PAYLOADS_SERVICE_CHECKS=false
      - DD_ENABLE_PAYLOADS_SKETCHES=false
    restart: always
    ports:
      - "5555:5555"
    labels:
      io.balena.features.balena-socket: "1"
